In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn

In [4]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()


# Explore Data

In [8]:
print("keys of iris_dataset: \n{}".format(iris_dataset.keys()))

keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [11]:
print(iris_dataset['DESCR'][:600]+"\n....")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
          
....


In [12]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [13]:
print("Target names: {}".format(iris_dataset['feature_names']))

Target names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']



The data is an array with the measures 

In [17]:
print("Target names: {}".format(type(iris_dataset['data'])))
print("Target names: {}".format(iris_dataset['data'].shape))
print("Target names: {}".format(iris_dataset['data'][:10]))

Target names: <class 'numpy.ndarray'>
Target names: (150, 4)
Target names: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]



The target array contains the species of each of the flower that were measuared

In [23]:
print("Target names: {}".format(type(iris_dataset['target'])))
print("Target names: {}".format(iris_dataset['target'].shape))
print("Target names: {}".format(iris_dataset['target'][:150]))

Target names: <class 'numpy.ndarray'>
Target names: (150,)
Target names: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


0 means sentosa. 
1 means versicolor. 
2 means virginica. 


# Training and Testing Data